//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public System.DateTime Datelspol { get; set; }
        public Nullable<decimal> Summa { get; set; }
        public string Name { get; set; }
    }
}
